import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layouts/Navbar'
import { AppProvider } from '@/components/contexts/AppProvider'
import { QueryProvider } from '@/components/contexts/QueryProvider'
import { Toaster } from 'react-hot-toast'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ReduxProvider } from '@/components/contexts/ReduxProvider'
import 'react-image-crop/dist/ReactCrop.css'
const inter = Inter({ subsets: ['latin'] })

// import { dir } from 'i18next'
// import { languages } from '@/utils/i18next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// export async function generateStaticParams() {
//   return languages.map((lng) => ({ lng }))
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {

  return (
    // <html lang={params?.lang ?? 'en'} dir={dir(params?.lang)}>

    <html >
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ReduxProvider>
            <QueryProvider>
              <AppProvider >
                <Navbar />
                {children}
                <Toaster />
              </AppProvider>
            </QueryProvider>
          </ReduxProvider>
        </AppRouterCacheProvider>

      </body>
    </html>
  )
}
